### ISSUE TITLE
Green timeline sections and video time in brackets not appearing until page refreshed

### ISSUE THREAD

**Issue by SigmaTheDJ** [ajayyy/SponsorBlock#1754]
Often when I click on a video that has ads in it, SponsorBlock does not show the green timeline sections, nor the adjusted video time in brackets. It will still skip the marked ads, so the core functionality is still working, but it doesn't highlight where the ads are. If I manually refresh the page, the green sections and adjusted video time in brackets both show up.

When initially clicking on a video: -

![1](https://github.com/ajayyy/SponsorBlock/assets/65978073/af5d4713-8257-420b-ba1f-9b8def0a9518)

After manually refreshing the page: -

![2](https://github.com/ajayyy/SponsorBlock/assets/65978073/65158573-30f7-4cfe-9368-dce55a8f0d9f)

This started happening around a week ago. I'm using Firefox 113.0.1 on Windows 10.

**Comment by mini-bomba** [comment]
What's the version of SB where this issue appears?

**Comment by ajayyy** [comment]
5.4.8 should fix this

**Comment by SigmaTheDJ** [comment]
It's still not working properly after updating to 5.4.8, for example: -

When initially clicking on a video: -

![1](https://github.com/ajayyy/SponsorBlock/assets/65978073/7d8154cd-551e-48a9-878f-a6186354eefd)

After refreshing the page: -

![2](https://github.com/ajayyy/SponsorBlock/assets/65978073/9be51127-276d-44e2-8f06-065e02318f44)
