### ISSUE TITLE
Fix Android version

### ISSUE THREAD

**Issue by Gorzen** [ajayyy/SponsorBlock#588]
Will SponsorBlock be available in Firefox for Android?

**Comment by ajayyy** [comment]
It works on the old Firefox for Android

**Comment by ajayyy** [comment]
You can try installing it using https://www.ghacks.net/2020/10/01/you-can-now-install-any-add-on-in-firefox-nightly-for-android-but-it-is-complicated/, but it doesn't seem to work yet. It seems Firefox nightly still is missing some APIs that SponsorBlock uses.

**Comment by ajayyy** [comment]
Actually, it seems the mobile version is broken in general

**Comment by ajayyy** [comment]
Fixed in https://github.com/ajayyy/SponsorBlock/pull/589

**Comment by Gorzen** [comment]
Great ! Thanks for all the comments 🥳

**Comment by Tomatoide** [comment]
Hi, unforetunately sponsorblock still doesn't work (at least for me) on latest fenix nightly and latest sponsorblock... It still has the same issues aka:
- doesnt work at all on first video
- on second video highlighted segments start to appear but no skipping
- albeit minor but icon is still broken in addons menu

**Comment by ajayyy** [comment]
@Tomatoide Yea, it seems Fenix is still not ready. It works in Kiwi browser though.

**Comment by Tomatoide** [comment]
the thing is it used to work in earlier fenix versions then it just started to work randomly then now it stopped completely

**Comment by Ra-Na** [comment]
I tried it with Firefox Nightly, and it recognizes and indicates the sponsor sections, but the buttons do not appear and the sponsor sections are not skipped

**Comment by Tomatoide** [comment]
on latest iceraven, skipping works sometimes, just randomly it starts working, until it stops working again

**Comment by Tomatoide** [comment]
on embedded youtube videos it works fine, but on youtube itself skipping rarely works

**Comment by Frejoh466** [comment]
> 
> 
> on embedded youtube videos it works fine, but on youtube itself skipping rarely works

I'm only getting the addon to work on Firefox Nightly when I request the desktop site (haven't tried embedded), and not on the m.youtube.com site. So you could try the desktop site instead.
