### ISSUE TITLE
SponsorBlock fails to work on Invidious

### ISSUE THREAD

**Issue by markozajc** [ajayyy/SponsorBlock#906]
SponsorBlock doesn't seem to work on any Invidious instance. Configuring it to use a dummy HTTP server reveals that a request to the segment server on the `/api/skipSegments/` endpoint is made for a video on youtube.com, but not on an Invidious instance, even for the same video in the same browser.
Tested browsers:
* Firefox 88.0.1 (my usual profile; security.csp.enable enabled)
* Firefox 88.0.1 (my usual profile; security.csp.enable disabled)
* Firefox 88.0.1 (brand new profile; security.csp.enable enabled)
* Firefox 88.0.1 (brand new profile; security.csp.enable disabled)
* ungoogled chromium 90.0.4430.212 (not in incognito mode)

Tested sites:
* youtube.com (working as usual)
* invidious.snopyta.org (doesn't work; version 8bd2669)
* yewtu.be (doesn't work; version 0db23f9)
* invidious.si  (doesn't work; version 0db23f9; personal, mapped to a LAN IP address in /etc/hosts)

All tests were performed on Debian Bookworm/12.
I've tested both the webstore and the beta version of SponsorBlock. I've gone through the devtools console in all cases and the only related thing I found appeared in ungoogled chromium (for all Invidious instances on both tested SponsorBlock versions)
```
Denying load of chrome-extension://<SponsorBlock's ID>/libs/Source+Sans+Pro.css. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
Denying load of chrome-extension://<SponsorBlock's ID>/popup.css. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
```
The extension itself always reports the error 'No segments found'.
This issue seems mildly related to #815, but I rather opened a new issue since the issue seems to affect all instances, not just the ones accessed over a LAN IP address.
SponsorBlock has worked on Invidious previously, but I don't use YouTube enough to determine when (or why) it broke. I remember it last working about a week ago, but it could've been less than that.

**Comment by ajayyy** [comment]
Maybe fixed by https://github.com/ajayyy/SponsorBlock/commit/da5de43121b2bb63df563de3e2232111bee1f0dc ?

Try Chrome: https://github.com/ajayyy/SponsorBlock/suites/3575542610/artifacts/85931983
Firefox: https://github.com/ajayyy/SponsorBlock/suites/3575542610/artifacts/85931985

**Comment by markozajc** [comment]
Thanks for the quick update!
I've tested it in ungoogled chromium, and the issue is indeed gone.

**Comment by sdfg2** [comment]
I'm getting the same thing.  I'm running 3.5.1 (latest at the time of writing) on Vivaldi.  Same errors found.  I tried the unpacked extension link, still doesn't work.

**Comment by markozajc** [comment]
CloudTube is not Invidious, you might want to open a separate issue.
Invidious support works fine for me on Firefox and Ungoogled Chromium with SB 3.5.1

**Comment by markozajc** [comment]
I believe the backend used doesn't matter to SB, as it parses the video ID from the site itself.

**Comment by sdfg2** [comment]
> I believe the backend used doesn't matter to SB, as it parses the video ID from the site itself.

Yes, I know, what I mean is that I got rid of CloudTube to check the Invidious instance directly.

**Comment by markozajc** [comment]
Right, my bad.

**Comment by sdfg2** [comment]
I had a suspicion and it proved correct.  Previously I was using http to connect to my instances.  I setup https and it works.
